### ISSUE TITLE
import stl

### ISSUE THREAD

**Issue by sirgogo** [nschloe/pygmsh#133]
Hi, I am trying to import an STL file and I get an error:
```
% python
Python 3.5.3 |Intel Corporation| (default, Apr 27 2017, 18:08:47)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import meshio as io
>>> io.read('./data/03_FULL_DELIVERY_22/VHP22_STL_FILES/VHPC_Heart.stl',file_format='stl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/intel/intelpython3/lib/python3.5/site-packages/meshio/helpers.py", line 121, in read
    return format_to_reader[file_format].read(filename)
KeyError: 'stl'
```
Any ideas?

**Comment by gdmcbain** [comment]
* This refers to [meshio](https://github.com/nschloe/meshio), not pygmsh; I've launched meshio#177.

**Comment by nschloe** [comment]
Alright, let's follow it up on meshio#177.
