### ISSUE TITLE
cannot extrude surface

### ISSUE THREAD

**Issue by tcaduser** [nschloe/pygmsh#157]
In the attached the file I am trying to create a volume by extruding a Plane Surface.  It is using the opencascade factory.  Could you please let me know what the issue is?
```
$ ~/anaconda3/bin/python finfet.py
Traceback (most recent call last):
  File "finfet.py", line 49, in <module>
    surf=create_fin_surface(geom, h=h_fin, w=w_fin, l=l_fin, cr=corner_radius)
  File "finfet.py", line 37, in create_fin_surface
    vol = geom.extrude(surface, translation_axis=[l, 0, 0])
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pygmsh/opencascade/geometry.py", line 195, in extrude
    assert isinstance(input_entity, SurfaceBase)
AssertionError
```
```python
import pygmsh
geom = pygmsh.opencascade.Geometry(
    characteristic_length_min=0.1,
    characteristic_length_max=0.1,
    )

def create_fin_surface(geom, h, w, l, cr, lcar=100):
    f = 0.5*w
    y = [-f,-f+cr, +f-cr, +f]
    z = [0.0, h-cr, h]
    f = 0.5 * cr
    x = [-f, f]
    points = []
    points.append(geom.add_point((x[0], y[0], z[0]), lcar=lcar))
    points.append(geom.add_point((x[0], y[0], z[1]), lcar=lcar))
    points.append(geom.add_point((x[0], y[1], z[1]), lcar=lcar))
    points.append(geom.add_point((x[0], y[1], z[2]), lcar=lcar))
    points.append(geom.add_point((x[0], y[2], z[2]), lcar=lcar))
    points.append(geom.add_point((x[0], y[2], z[1]), lcar=lcar))
    points.append(geom.add_point((x[0], y[3], z[1]), lcar=lcar))
    points.append(geom.add_point((x[0], y[3], z[0]), lcar=lcar))

    lines = []
    lines.append(geom.add_line(points[0], points[1]))
    lines.append(geom.add_circle_arc(points[1], points[2], points[3]))

    lines.append(geom.add_line(points[3], points[4]))
    lines.append(geom.add_circle_arc(points[4], points[5], points[6]))
    lines.append(geom.add_line(points[6], points[7]))
    lines.append(geom.add_line(points[7], points[0]))

    line_loop=geom.add_line_loop(lines)
    surface=geom.add_plane_surface(line_loop)
    vol = geom.extrude(surface, translation_axis=[l, 0, 0])
    return vol

h_fin = 25
w_fin = 10
l_fin = 100
x_fin = -0.5*l_fin
corner_radius = 1

surf = create_fin_surface(geom, h=h_fin, w=w_fin, l=l_fin, cr=corner_radius)
print(geom.get_code())
```

**Comment by tcaduser** [comment]
This was installed using
pip install pygmsh

**Comment by tcaduser** [comment]
In the attached file, everything was generated by pygmsh, except for the extrusion at the end.  Which works when run in gmsh.
[foo.txt](https://github.com/nschloe/pygmsh/files/1813956/foo.txt)

**Comment by phbphy** [comment]
So far, I've always used the built_in geometry kernel. If your replace 
`geom = pygmsh.opencascade.Geometry(...)` with `geom = pygmsh.built_in.Geometry()` it will work. However, I'm not sure if this is the proper way / what is wrong with using the opencascade kernel.

**Comment by tcaduser** [comment]
The opencascade kernel is needed for boolean operations

**Comment by nschloe** [comment]
This was actually a bug in pygmsh. Fixed now.

**Comment by tcaduser** [comment]
Thank you.  Can I get the fix using pip, or do I need to install from the repo?

**Comment by nschloe** [comment]
pip
