### ISSUE TITLE
pygmsh issues mac os x with anaconda python

### ISSUE THREAD

**Issue by tcaduser** [nschloe/pygmsh#161]
When importing pygmsh using Anaconda 2 or Anaconda 3 from
https://continuum.io

The program stops due to the matplotlib mac os x backend not being compatible with a non-framework install of python. 
```
>>> import pygmsh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/anaconda/lib/python2.7/site-packages/pygmsh/__init__.py", line 12, in <module>
    from . import built_in
  File "/Users/user/anaconda/lib/python2.7/site-packages/pygmsh/built_in/__init__.py", line 3, in <module>
    from .geometry import Geometry
  File "/Users/user/anaconda/lib/python2.7/site-packages/pygmsh/built_in/geometry.py", line 21, in <module>
    from ..helpers import _is_string
  File "/Users/user/anaconda/lib/python2.7/site-packages/pygmsh/helpers.py", line 12, in <module>
    import voropy
  File "/Users/user/anaconda/lib/python2.7/site-packages/voropy/__init__.py", line 13, in <module>
    from . import smoothing
  File "/Users/user/anaconda/lib/python2.7/site-packages/voropy/smoothing.py", line 5, in <module>
    from matplotlib import pyplot as plt
  File "/Users/user/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/user/anaconda/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/Users/user/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

To fix this, I have to change the backend by:
```
echo "backend: Tkagg" ~/.matplotlib/matplotlibrc
```

Would it be possible to defer loading of voropy, unless it is used?  Or could you catch the exception, and change the backend being imported?

**Comment by nschloe** [comment]
Hm, tough. Lazy-loading voropy is certainly a possibility, but then if you have a 2D mesh and want to use Lloyd (which is definitely recommendable) you'd run into the same issue. The problem apparently is matplotlib, which you don't even need in this case, so lazy-loading matplotlib in voropy would probably fix it. Then again, matplotlib has to be lazy-loaded in _all_ dependent libraries, and that doesn't seem like a maintainable solution.

For what it's worth, whenever I need to run a Python program with matplotlib on platform without graphics support (think SSHing into a server), I do
```python
MPLBACKEND=Agg python something.py
```
That's more or less what you're doing right now when setting the default backend.

Is there a problem with your solution at all?

**Comment by nschloe** [comment]
Okay, I've updated voropy to only optionall pull in matplotlib.

**Comment by tcaduser** [comment]
When I first tried to use pygmsh, I initially gave up because of this error, and the errors about python 2.  I think it is good to have things work when someone first tries your useful project.

**Comment by nschloe** [comment]
Glad it works better for you now
