### ISSUE TITLE
Syntax errors running tests

### ISSUE THREAD

**Issue by bobmyhill** [nschloe/pygmsh#174]
After installation of pygmsh using pip (python 2.7), I tried running one of the test scripts (specifically test_logo.py), and got a long list of error messages printed to stdout (copied at the bottom of this page).

The same thing happens within a conda environment running python 3.6, and also installing directly from this repository (via sudo -H python setup.py install --force).

Any ideas for how I could fix this? Has something changed with Gmsh recently? 

Thanks! 

```
Info : Running 'gmsh -3 -bin /tmp/tmpWcM2yC.geo -o /tmp/tmpesAkcq.msh -optimize' [Gmsh 2.10.1, 1 node, max. 1 thread]
Info    : Started on Fri Apr 27 19:16:17 2018
Info    : Reading '/tmp/tmpWcM2yC.geo'...
Error   : '/tmp/tmpWcM2yC.geo', line 2 : syntax error (")
Error   : '/tmp/tmpWcM2yC.geo', line 6 : syntax error ({)
Error   : '/tmp/tmpWcM2yC.geo', line 8 : syntax error ({)
Error   : '/tmp/tmpWcM2yC.geo', line 10 : syntax error ({)
Error   : '/tmp/tmpWcM2yC.geo', line 12 : syntax error ({)
Error   : '/tmp/tmpWcM2yC.geo', line 14 : syntax error ({)
Error   : '/tmp/tmpWcM2yC.geo', line 16 : syntax error ({)
Error   : '/tmp/tmpWcM2yC.geo', line 18 : syntax error ({)
Error   : '/tmp/tmpWcM2yC.geo', line 20 : syntax error ({)
Warning : '/tmp/tmpWcM2yC.geo', line 21 : Unknown surface 1
Error   : '/tmp/tmpWcM2yC.geo', line 21 : syntax error (Delete)
Error   : '/tmp/tmpWcM2yC.geo', line 21 : syntax error (})
Error   : '/tmp/tmpWcM2yC.geo', line 21 : syntax error (;)
Error   : '/tmp/tmpWcM2yC.geo', line 21 : syntax error (})
Error   : '/tmp/tmpWcM2yC.geo', line 23 : syntax error ({)
Error   : '/tmp/tmpWcM2yC.geo', line 24 : Unknown variable 'bo1'
Error   : '/tmp/tmpWcM2yC.geo', line 24 : syntax error (Delete)
Error   : '/tmp/tmpWcM2yC.geo', line 24 : syntax error (})
Error   : '/tmp/tmpWcM2yC.geo', line 24 : syntax error (;)
Error   : '/tmp/tmpWcM2yC.geo', line 24 : syntax error (})
Error   : '/tmp/tmpWcM2yC.geo', line 26 : syntax error ({)
Error   : '/tmp/tmpWcM2yC.geo', line 28 : syntax error ({)
Error   : Too many errors: aborting parser...
Info    : Done reading '/tmp/tmpWcM2yC.geo'
Info    : Meshing 1D...
Info    : Done meshing 1D (0 s)
Info    : Meshing 2D...
Info    : Done meshing 2D (5.00679e-06 s)
Info    : Meshing 3D...
Info    : Done meshing 3D (0 s)
Info    : 0 vertices 0 elements
Info    : Writing '/tmp/tmpesAkcq.msh'...
Info    : Done writing '/tmp/tmpesAkcq.msh'
Info    : Stopped on Fri Apr 27 19:16:17 2018
Traceback (most recent call last):
  File "test_logo.py", line 59, in <module>
    plot('logo.png', *test())
  File "test_logo.py", line 51, in test
    points, cells, _, _, _ = pygmsh.generate_mesh(geom, num_lloyd_steps=0)
  File "build/bdist.linux-x86_64/egg/pygmsh/helpers.py", line 140, in generate_mesh
    
AssertionError: Gmsh exited with error (return code 1).
```

**Comment by nschloe** [comment]
> Gmsh 2.10.1

You need Gmsh 3.*.

**Comment by bobmyhill** [comment]
Thanks! Frustratingly, gmsh 2.10.1 is the most up-to-date in the ubuntu repo, but at least the newer version is trivial to find.
