### ISSUE TITLE
Cant import pygmsh 4.3.5

### ISSUE THREAD

**Issue by jorgensd** [nschloe/pygmsh#218]
Pygmsh installed with `pip3 install pygmsh --upgrade`
Crashes at import
```
Traceback (most recent call last):
  File "bench_mesh.py", line 1, in <module>
    import pygmsh
  File "/home/dokken/Documents/VirtualEnvironments/dolfin_lfs/env/lib/python3.5/site-packages/pygmsh/__init__.py", line 7, in <module>
    from . import built_in
  File "/home/dokken/Documents/VirtualEnvironments/dolfin_lfs/env/lib/python3.5/site-packages/pygmsh/built_in/__init__.py", line 3, in <module>
    from .geometry import Geometry
  File "/home/dokken/Documents/VirtualEnvironments/dolfin_lfs/env/lib/python3.5/site-packages/pygmsh/built_in/geometry.py", line 7, in <module>
    from ..helpers import _is_string
  File "/home/dokken/Documents/VirtualEnvironments/dolfin_lfs/env/lib/python3.5/site-packages/pygmsh/helpers.py", line 122
    suffix = f".{mesh_file_type}"
```

**Comment by nschloe** [comment]
You'll need at least Python 3.6.

**Comment by jorgensd** [comment]
Oh dear, that's a shame. FEniCS docker images are not  built with python 3.6.

**Comment by jhale** [comment]
I'll sort this out now Jorgen, I have a branch with newer Ubuntu which is
probably based off 3.6.

**Comment by nschloe** [comment]
It's also a little harsh of pygmsh to require that version. Will look at it later.

**Comment by gdmcbain** [comment]
Sorry, my fault. It looks like just an f-string. Should be easy to replace with something like
```python
suffix = ".{}".format(mesh_file_type}
```
But I'm away from the terminal till tomorrow.

**Comment by nschloe** [comment]
Will release in a few minutes. (https://github.com/nschloe/pygmsh/pull/219)

**Comment by nschloe** [comment]
Alright, fixed now.
