### ISSUE TITLE
Help with booleans

### ISSUE THREAD

**Issue by slagwad** [nschloe/pygmsh#296]
Hello, I hope you can help me, this seems trivial but I can't figure it out.

cone1 = geom.add_cone([0.001*c/2, 0.001*c/2, 0.001*0], [0.001*0, 0.001*0, 0.001*rad], radius0=0.001*rad, radius1=0.001*0)

rectangle = geom.add_rectangle([0.0, 0.0, 0.0], 0.001*c, 0.001*c)
cbase = geom.extrude(rectangle, [0, 0, 0.001*1])
conenbase = geom.boolean_union([cone1, cbase],delete_first=True, delete_other=True)

**produces this error:**

Traceback (most recent call last):
  File "pygmsh_test4_1.py", line 60, in <module>
    conenbase = geom.boolean_union([cone1, cbase],delete_first=True, delete_other=True)
  File "/home/elmeruser/anaconda3/lib/python3.7/site-packages/pygmsh/opencascade/geometry.py", line 190, in boolean_union
    delete_other=delete_other,
  File "/home/elmeruser/anaconda3/lib/python3.7/site-packages/pygmsh/opencascade/geometry.py", line 113, in _boolean_operation
    e.dimension == dim
AttributeError: 'tuple' object has no attribute 'dimension'

It is bizarre because the exact same boolean_union command elsewhere in my code works fine.

Similarly, I am not able to get this code to work:
geom.boolean_intersection([air], [zno_all])

**it gives this error:**
Traceback (most recent call last):
  File "pygmsh_test4_1.py", line 71, in <module>
    geom.boolean_intersection([air], [zno_all])
  File "/home/elmeruser/anaconda3/lib/python3.7/site-packages/pygmsh/opencascade/geometry.py", line 171, in boolean_intersection
    assert len(entities) > 1
AssertionError

Thanks in advance!

**Comment by gdmcbain** [comment]
> AttributeError: 'tuple' object has no attribute 'dimension'

`cbase`, produced by extrusion, is a tuple. Pick out the item that is intended rather than passing the whole tuple. It might be `cbase[1]`.

**Comment by slagwad** [comment]
Thank you.  That worked.  I earlier tried to use geo.add_box and ran into errors so I ended up with the code above attempting to make a box by extruding a rectangle.  I went back and tried add_box and it no longer was causing any errors.
