### ISSUE TITLE
Tests don't run in 6.0.4

### ISSUE THREAD

**Issue by frli8848** [nschloe/pygmsh#310]
I tried to run the tests for pygmsh-6.0.4 but all assertions don't work since there is no compute_volume in the helpers.py file. That is,

`pygmsh-6.0.4 # grep compute_volume pygmsh/helpers.py`

returns nothing. I also had to change the lines

`from helpers import compute_volume`

to 

`from pygmsh.helpers import compute_volume`

 in the test files to find helpers.py and then I get

```
$ python test_pipes.py
Traceback (most recnent call last):
  File "test_pipes.py", line 4, in <module>
    from pygmsh.helpers import compute_volume
ImportError: cannot import name 'compute_volume'
```

since there is no compute_volume.

**Comment by nschloe** [comment]
pygmsh does not support Python 2.

**Comment by frli8848** [comment]
I'm running:

```
$ python --version
Python 3.6.9

```

Where is the compute_volume function located if its not in the file `pygmsh/helpers.py`? And, on my Genoo box I have pygmsh installed in:
```
# ls /usr/lib64/python3.6/site-packages/pygmsh/
__about__.py  __init__.py  __pycache__  built_in  helpers.py  opencascade
```

**Comment by nschloe** [comment]
It's in `test/helpers.py`.

**Comment by frli8848** [comment]
Aha, I think this file is missing in the 6.0.4 tar.gz file.

**Comment by nschloe** [comment]
You're right! I'll fix that.

**Comment by nschloe** [comment]
Fixed in 6.0.5.

**Comment by frli8848** [comment]
6.0.5 works but I get a few failures and warnings. I have installed the latest versions of these packages:
```
dev-python/meshio-4.0.2
dev-python/optimesh-0.6.0
dev-python/meshzoo-0.5.3
dev-python/meshplex-0.12.0
dev-python/termplotlib-0.2.3
dev-python/quadpy-0.14.5
dev-python/orthopy-0.6.2
```
that I could find at pypi.org

Here's the results of the failing tests:

```
$ python test_circle_transform.py 
Info    : Running 'gmsh -3 /tmp/tmplwxs_eje.geo -format msh -bin -o /tmp/tmp4948zohk.msh' [Gmsh 4.4.1, 1 node, max. 1 thread]

-snip-

Info    : Stopped on Fri Feb 21 07:07:07 2020
Traceback (most recent call last):
  File "test_circle_transform.py", line 26, in <module>
    meshio.write("circle_transformed.vtk", *test())
TypeError: write() argument after * must be an iterable, not Mesh
```
```
$ python test_in_surface.py

-snip-

Info    : Writing '/tmp/tmp9xhg_zc9.msh'...
Info    : Done writing '/tmp/tmp9xhg_zc9.msh'
Info    : Stopped on Fri Feb 21 07:13:12 2020
WARNING:root:VTK requires 3D points, but 2D points given. Appending 0 third component.
```
 ```
$ python test_logo.py

-snip-

Info    : Done writing '/tmp/tmp3f5dcw7_.msh'
Info    : Stopped on Fri Feb 21 07:14:22 2020
Traceback (most recent call last):
  File "test_logo.py", line 47, in <module>
    points, cells = optimesh.lloyd(mesh.points, mesh.cells["triangle"], 1.0e-5, 10000)
AttributeError: module 'optimesh' has no attribute 'lloyd'

```

```
$ python test_meshio_logo.py

-snip-

Info    : 511 vertices 1035 elements
Info    : Writing '/tmp/tmpy22uscm9.msh'...
Info    : Done writing '/tmp/tmpy22uscm9.msh'
Info    : Stopped on Fri Feb 21 07:15:30 2020
Traceback (most recent call last):
  File "test_meshio_logo.py", line 35, in <module>
    plot("meshio_logo.png", test())
TypeError: plot() missing 1 required positional argument: 'cells'
```

**Comment by nschloe** [comment]
All fixed by https://github.com/nschloe/pygmsh/pull/312.
