### ISSUE TITLE
Generating (triply) periodic meshes using pygmsh

### ISSUE THREAD

**Issue by bhaveshshrimali** [nschloe/pygmsh#318]
Hello @nschloe , 

Thanks for pygmsh, it is indeed a fantastic tool. 

I was wondering if there are any examples/tutorials to generate matching meshes using pygmsh required to impose periodic boundary conditions, for instance for a geometry like
 
![trialSpheres](https://user-images.githubusercontent.com/22624037/75646605-cc4bb580-5c0f-11ea-9aa3-ceefce116a3c.png) 

#193 does seem to have something similar albeit in 2D. I am working my way through the Gmsh tutorials / pygmsh docs to generate a matching mesh but was wondering if there are any existing examples on generating periodic meshes in 3D.

**Comment by nschloe** [comment]
Note that pygmsh is merely an interface to gmsh. How would you accomplish what you're trying to do in gmsh? If you don't know, ask the gmsh folks. If you do know, post some gmsh code here and we can work out how to translate it to pygmsh.

**Comment by bhaveshshrimali** [comment]
I have not worked extensively with `Gmsh` and never with the Gmsh API. Here is a quick code that I wrote to get started with pygmsh. It attempts to mesh a unit cube with matching nodes on opposite faces. I believe this should be a good place to start. 

```python3
import pygmsh as pm
import meshio

def generateGmshMesh():

    geom = pm.opencascade.Geometry()
    origin = geom.add_point([0., 0., 0.], 0.01)
    right = geom.add_point([1., 0., 0.], 0.01)
    top = geom.add_point([0., 1., 0.], 0.01)
    front = geom.add_point([0., 0., 1.], 0.01)
    right_front = geom.add_point([1., 0, 1], 0.01)
    right_top = geom.add_point([1., 1., 0], 0.01)
    right_top_front = geom.add_point([1,1,1], 0.01)
    top_front = geom.add_point([0, 1, 1], 0.01)
    
    e1 = geom.add_line(origin, right)
    e2 = geom.add_line(origin, top)
    e3 = geom.add_line(origin, front)
    
    e1s1 = geom.add_line(right, right_top) #line_right_right_top
    e1s2 = geom.add_line(right_top, right_top_front)
    e1s3 = geom.add_line(right_top_front, right_front)
    e1s4 = geom.add_line(right_front, right)

    e2s1 = geom.add_line(top, top_front) #line_right_right_top
    e2s2 = geom.add_line(top_front, right_top_front)
    # e2s3 = geom.add_line(right_top_front, right_top) # = -e1s2
    e2s4 = geom.add_line(right_top, top)

    e3s1 = geom.add_line(front, right_front) #line_right_right_top
    # e3s2 = geom.add_line(right_top_front, top_front)
    # e3s3 = geom.add_line(right_top_front, right_front)
    e3s4 = geom.add_line(top_front, front)

    l1 = geom.add_line_loop([e1s1, e1s2, e1s3, e1s4])
    rightFace = geom.add_plane_surface(l1)
    l2 = geom.add_line_loop([e2, e2s1, e3s4, e3])
    leftFace = geom.add_plane_surface(l2)
    l3 = geom.add_line_loop([e2s1, e2s2, e1s2, e2s4])
    topFace = geom.add_plane_surface(l3)
    l4 = geom.add_line_loop([e3, e3s1, e1s4, e1])
    bottomFace = geom.add_plane_surface(l4)
    l5 = geom.add_line_loop([e1, e1s1, e2s4, e2])
    backFace = geom.add_plane_surface(l5)
    l6 = geom.add_line_loop([e3s1, e1s3, e2s2, e3s4])
    frontFace = geom.add_plane_surface(l6)

    surface_loop = geom.add_surface_loop([rightFace, backFace, leftFace, frontFace, topFace, bottomFace])
    unitcube = geom.add_volume(surface_loop)

    geom.add_raw_code("Periodic Surface {{ {0} }} = {{ {1} }};".format(rightFace.id, leftFace.id))
    geom.add_raw_code("Periodic Surface {{ {0} }} = {{ {1} }};".format(topFace.id, bottomFace.id))
    geom.add_raw_code("Periodic Surface {{ {0} }} = {{ {1} }};".format(frontFace.id, backFace.id))

    points, cells, point_data, cell_data, field_data = pm.generate_mesh(geom, geo_filename="out.geo")
    meshio.write_points_cells("test.xdmf", points, cells, cell_data=cell_data)

```

but I get the following error: 

```
Traceback (most recent call last):
  File ".\read_geom.py", line 212, in <module>
    generateGmshMesh(sph, sph, rad)
  File ".\read_geom.py", line 137, in generateGmshMesh
    points, cells, point_data, cell_data, field_data = pm.generate_mesh(geom, geo_filename="out.geo")
  File "C:\Users\Bhavesh\AppData\Local\Programs\Python\Python37\lib\site-packages\pygmsh\helpers.py",
line 141, in generate_mesh
    p.returncode
AssertionError: Gmsh exited with error (return code 1).
```
I checked the `out.geo` and the geometry seems to be created as desired. 

I am going to check the corresponding ID's again but the geometry seems to be fine. Any suggestions ?

**Comment by bhaveshshrimali** [comment]
I just noticed that if I load the generated `geo` file in Gmsh and use the GUI to generate a mesh, it does not give out any error. 

![output](https://user-images.githubusercontent.com/22624037/75701374-449a9100-5c79-11ea-94bc-bcdf17d616bd.png)


Am I missing something here?

**Comment by nschloe** [comment]
> Any suggestions ?

If the geo file is working and pygmsh is not, it's a pygmsh bug. If the geo file seems alright but not working, it's probably a good idea to get back to the gmsh devs with the file to see what's wrong.

**Comment by bhaveshshrimali** [comment]
The `geo` file seems to be working. I checked it for a coarser mesh and it generates the mesh without any problem. 

```
// This code was created by pygmsh v6.0.4.
SetFactory("OpenCASCADE");
p0 = newp;
Point(p0) = {0.0, 0.0, 0.0, 1};
p1 = newp;
Point(p1) = {1.0, 0.0, 0.0, 1};
p2 = newp;
Point(p2) = {0.0, 1.0, 0.0, 1};
p3 = newp;
Point(p3) = {0.0, 0.0, 1.0, 1};
p4 = newp;
Point(p4) = {1.0, 0, 1, 1};
p5 = newp;
Point(p5) = {1.0, 1.0, 0, 1};
p6 = newp;
Point(p6) = {1, 1, 1, 1};
p7 = newp;
Point(p7) = {0, 1, 1, 1};
l0 = newl;
Line(l0) = {p0, p1};
l1 = newl;
Line(l1) = {p0, p2};
l2 = newl;
Line(l2) = {p0, p3};
l3 = newl;
Line(l3) = {p1, p5};
l4 = newl;
Line(l4) = {p5, p6};
l5 = newl;
Line(l5) = {p6, p4};
l6 = newl;
Line(l6) = {p4, p1};
l7 = newl;
Line(l7) = {p2, p7};
l8 = newl;
Line(l8) = {p7, p6};
l9 = newl;
Line(l9) = {p5, p2};
l10 = newl;
Line(l10) = {p3, p4};
l11 = newl;
Line(l11) = {p7, p3};
ll0 = newll;
Line Loop(ll0) = {l3, l4, l5, l6};
s0 = news;
Plane Surface(s0) = {ll0};
ll1 = newll;
Line Loop(ll1) = {l1, l7, l11, l2};
s1 = news;
Plane Surface(s1) = {ll1};
ll2 = newll;
Line Loop(ll2) = {l7, l8, l4, l9};
s2 = news;
Plane Surface(s2) = {ll2};
ll3 = newll;
Line Loop(ll3) = {l2, l10, l6, l0};
s3 = news;
Plane Surface(s3) = {ll3};
ll4 = newll;
Line Loop(ll4) = {l0, l3, l9, l1};
s4 = news;
Plane Surface(s4) = {ll4};
ll5 = newll;
Line Loop(ll5) = {l10, l5, l8, l11};
s5 = news;
Plane Surface(s5) = {ll5};
sl0 = news;
Surface Loop(sl0) = {s0,s4,s1,s5,s2,s3};
vol0 = newv;
Volume(vol0) = {sl0};
Periodic Surface { s0 } = { s1 };
Periodic Surface { s2 } = { s3 };
Periodic Surface { s5 } = { s4 };
```

![outCoarse](https://user-images.githubusercontent.com/22624037/75701708-d60a0300-5c79-11ea-9dba-1805fc1e5269.png)

`pygmsh` still throws the same exception.

**Comment by nschloe** [comment]
With pygmsh and on the command line, I'm getting
```
Error   : 'out.geo', line 71 : Affine transformation requires at least 12 entries
Error   : 'out.geo', line 72 : Affine transformation requires at least 12 entries
Error   : 'out.geo', line 72 : Affine transformation requires at least 12 entries
```
towards the beginning of the output. I'm guessing this is the source of the issue.

**Comment by bhaveshshrimali** [comment]
I completely missed that in the raw code, however even after changing to
```python3
def generateGmshMesh(xc, pc, r):
    ...
    ...
    ...

    geom.add_raw_code("Periodic Surface {{ {0} }} = {{ {1} }} Translate {{ {2}, {3}, {4} }};".format(rightFace.id, leftFace.id, 1,0,0 ))
    geom.add_raw_code("Periodic Surface {{ {0} }} = {{ {1} }} Translate {{ {2}, {3}, {4} }};".format(topFace.id, bottomFace.id, 0,1,0 ))
    geom.add_raw_code("Periodic Surface {{ {0} }} = {{ {1} }} Translate {{ {2}, {3}, {4} }};".format(frontFace.id, backFace.id, 0,0,1 ))
```

which does seem to generate a `.geo` file that loads without the previous error, I get the following error
```
    points, cells, point_data, cell_data, field_data = pm.generate_mesh(geom, geo_filename="outCoarse.
geo")
TypeError: cannot unpack non-iterable Mesh object
```

**Comment by nschloe** [comment]
It's
```python
mesh = pm.generate_mesh(...)
```
Is there un-updated documentation somewhere?

**Comment by bhaveshshrimali** [comment]
Gotcha, thanks. My bad I was trying to build on #193 verbatim. Will work on booleans to add the spheres. Thanks again
