### ISSUE TITLE
pygmsh,Cylinder

### ISSUE THREAD

**Issue by ghazalemir** [nschloe/pygmsh#324]
Hi every Body,
I am trying to use this code to generat a cylinder and mesh it.
```python
from math import pi
import pygmsh
import meshio

def test():
    geom = pygmsh.opencascade.Geometry()
    geom.add_cylinder([0.0,0.0,0.0], [0.0,0.0,1.0], 20, 0.25*pi,char_length=1)
    mesh = pygmsh.generate_mesh(geom)
    #meshio.write("final.vtk", mesh)
    return mesh
meshio.write("opencascade_cylinder.vtk",test())
```
but I have this error:
```
runfile('C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code/1.py', wdir='C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code')
Is gmsh installed?
Traceback (most recent call last):

  File "<ipython-input-16-0c493db11ef0>", line 1, in <module>
    runfile('C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code/1.py', wdir='C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code')

  File "C:\Users\ghaza\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\ghaza\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code/1.py", line 19, in <module>
    meshio.write("opencascade_cylinder.vtk",test())

  File "C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code/1.py", line 16, in test
    mesh = pygmsh.generate_mesh(geom)

  File "C:\Users\ghaza\Anaconda3\lib\site-packages\pygmsh\helpers.py", line 123, in generate_mesh
    [gmsh_executable] + args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT

  File "C:\Users\ghaza\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\ghaza\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)

  File "C:\Users\ghaza\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by nschloe** [comment]
```
Is gmsh installed?
```
(Also, best make yourself familiar with GitHub markdown syntax, they have code blocks. https://guides.github.com/features/mastering-markdown/ Makes it easier to read.)

**Comment by ghazalemir** [comment]
Yes I think it is installed, Becuase when I import it there is no error.

**Comment by ghazalemir** [comment]
In fact I have installed pygmsh!

**Comment by nschloe** [comment]
Not pygmsh, _gmsh_. https://gmsh.info/

**Comment by ghazalemir** [comment]
You are right!
:)

**Comment by nschloe** [comment]
Cool. Feel free to close the issue if you have no more troubles with this.

**Comment by ghazalemir** [comment]
I installed the gmsh but unfortunately again I have that error.
#
runfile('C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code/1.py', wdir='C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code')
Reloaded modules: pytest
Is gmsh installed?
Traceback (most recent call last):

  File "<ipython-input-2-0c493db11ef0>", line 1, in <module>
    runfile('C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code/1.py', wdir='C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code')

  File "C:\Users\ghaza\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\ghaza\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code/1.py", line 19, in <module>
    meshio.write("opencascade_cylinder.vtk",test())

  File "C:/Users/ghaza/Documents/PhD/Documents/CFD-DEM course/Project/Code/1.py", line 16, in test
    mesh = pygmsh.generate_mesh(geom)

  File "C:\Users\ghaza\Anaconda3\lib\site-packages\pygmsh\helpers.py", line 123, in generate_mesh
    [gmsh_executable] + args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT

  File "C:\Users\ghaza\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\ghaza\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)

  File "C:\Users\ghaza\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified
#

**Comment by nschloe** [comment]
> (Also, best make yourself familiar with GitHub markdown syntax, they have code blocks. https://guides.github.com/features/mastering-markdown/ Makes it easier to read.)

You can edit your post for readability.
