### ISSUE TITLE
pygmsh.generate_mesh throws AttributeError: 'list' object has no attribute 'values'

### ISSUE THREAD

**Issue by stasbar** [nschloe/pygmsh#326]
Hello,
I'm facing strange problem.
When I try to run `pygmsh/test/test_extrusion_entities.py` on my macos, it's working fine. But when I start in on my Linux arch, it crashes with
```
Info    : Running 'gmsh -3 /tmp/tmphl05rhf4.geo -format msh -bin -o /tmp/tmphw9eq_n4.msh' [Gmsh 4.5.6, 1 node, max. 1 thread]
Info    : Started on Mon Apr 13 21:25:01 2020
Info    : Reading '/tmp/tmphl05rhf4.geo'...
Info    : Done reading '/tmp/tmphl05rhf4.geo'
Info    : Meshing 1D...
Info    : Meshing curve 1 (Line)
Info    : Done meshing 1D (0.000552 s)
Info    : Meshing 2D...
Info    : Done meshing 2D (5.7e-05 s)
Info    : Meshing 3D...
Info    : Done meshing 3D (3.9e-05 s)
Info    : 2 nodes 3 elements
Info    : Writing '/tmp/tmphw9eq_n4.msh'...
Info    : Done writing '/tmp/tmphw9eq_n4.msh'
Info    : Stopped on Mon Apr 13 21:25:01 2020
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    test()
  File "test.py", line 15, in test
    mesh = pygmsh.generate_mesh(geom)
  File "/home/stasbar/VapeTool-CoilMesher/venv/lib/python3.8/site-packages/pygmsh/helpers.py", line 165, in generate_mesh
    ncells = numpy.concatenate([numpy.concatenate(c) for c in mesh.cells.values()])
AttributeError: 'list' object has no attribute 'values'
```

on my macos I have
```
Gmsh 4.5.0-git-e396176

python 3.7.7

meshio==3.3.1
numpy==1.18.1
pycodestyle==2.5.0
pygmsh==6.0.2
```

On my arch Linux I have:
```
Gmsh 4.5.6

python 3.8.1 (python 3.7 throws the same error)

importlib-metadata==1.6.0
meshio==4.0.10
numpy==1.18.2
pygmsh==6.0.2
zipp==3.1.0

```

I'm not sure if the problem is related to `pygmsh`, but everything else on this machine seems to be working fine.

**Comment by nschloe** [comment]
Outdated meshio.

**Comment by stasbar** [comment]
Your are almost right, because the problem is that meshio is too new.  On my macos I have `meshio==3.3.1` when updated to `meshio==4.0.10` it throws the same error. When I downgraded on my arch It's working fine 👍

**Comment by nschloe** [comment]
Outdated pygmsh then. :)
