### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified: 

### ISSUE THREAD

**Issue by OKVMR** [nschloe/pygmsh#334]
So I'm doing a simple integral code from a book exercise. Even having the answer, I get an error trying to run the code. I'm using anaconda > spyder.
Heres the code:
from numpy import exp

def f(x):
    return exp(-x**2)

def F(x):
    a = 0
    b = x
    N = 1000
    h = (b - a) / N
    oddSum = 0
    for k in range(1, N, 2):
        oddSum += f(a + k*h)
        
        evenSum = 0
        for k in range(2, N, 2):
            evenSum += f(a + k*h)
            
            return 1 / 3 * h * (f(a) + f(b) + 4 * oddSum + 2 * evenSum)

Heres the full error:
runfile('C:/Users/Olivia/Documents/Sem 2 Computing Yr 2/Session 2/3.2 Dawson\'s Integral.py', wdir='C:/Users/Olivia/Documents/Sem 2 Computing Yr 2/Session 2/3.2 Dawson')
Traceback (most recent call last):

  File "<ipython-input-5-c3001d385352>", line 1, in <module>
    runfile('C:/Users/Olivia/Documents/Sem 2 Computing Yr 2/Session 2/3.2 Dawson\'s Integral.py', wdir='C:/Users/Olivia/Documents/Sem 2 Computing Yr 2/Session 2/3.2 Dawson')

  File "C:\Users\Olivia\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 695, in runfile
    os.chdir(wdir)

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/Users/Olivia/Documents/Sem 2 Computing Yr 2/Session 2/3.2 Dawson'

**Comment by OKVMR** [comment]
Sorry for the poor formatting, it changed upon posting!
