### ISSUE TITLE
Boolean fragments example

### ISSUE THREAD

**Issue by bhaveshshrimali** [nschloe/pygmsh#336]
Hi Nico,
I guess a rather naive question. I am trying to rewrite the boolean fragments tutorial, with an approach similar to what is given [here](https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/tutorial/t16.geo) with `pygmsh`

I am looking to generate a conformal mesh of a circle in a square (not hole), so far I have tried

```python
import pygmsh
geom = pygmsh.opencascade.Geometry(characteristic_length_min=0.05,
  characteristic_length_max=0.05)

rect = geom.add_rectangle([0,0,0],1., 1.)
# rp = geom.add_physical(rect, label=1)
circ = geom.add_disk([0.5, 0.5, 0], 0.2)

outerpart = geom.boolean_fragments([rect], [circ], delete_other=False)
# union = geom.boolean_union([outerpart, circ2])
msh = pygmsh.generate_mesh(geom)
``` 
But either the *conformal*-ity of the mesh is lost (I get a simple `UnitSquare`-mesh) or I get a hole inside a square. 

I know I might be missing something very rudimentary but can't seem to figure out. 

Thanks

**Comment by nschloe** [comment]
I'm getting this:
![g](https://user-images.githubusercontent.com/181628/82646854-966a0c00-9c15-11ea-9b19-2aa550ac7a3d.png)

Looks alright. Perhaps you need to update your gmsh? (Just a wild guess.)

**Comment by bhaveshshrimali** [comment]
gmsh is version `4.5.6`. I reinstalled meshio and pygmsh (as the geo file seems sane to me)
```cpp
// This code was created by pygmsh v6.0.4.
SetFactory("OpenCASCADE");
Mesh.CharacteristicLengthMin = 0.1;
Mesh.CharacteristicLengthMax = 0.1;
s0 = news;
Rectangle(s0) = {0.0, 0, 0, 1.0, 1.0};
s1 = news;
Disk(s1) = {0.5, 0.5, 0, 0.2};
bo1[] = BooleanFragments{ Surface{s0}; Delete; } { Surface{s1}; };
```
however now, 
```python
import pygmsh, meshio, os
import matplotlib.pyplot as plt
filepath = os.getcwd()
geom = pygmsh.opencascade.Geometry(0.1, 0.1)
rect = geom.add_rectangle([0.,0,0], 1., 1.)
circ = geom.add_disk([0.5, 0.5, 0], 0.2)
outerpart = geom.boolean_fragments([rect], [circ], delete_other=False)
msh = pygmsh.generate_mesh(geom, geo_filename=os.path.join(filepath, "trial.geo")) # -->
print(msh.cells)
cells_tri = np.vstack((cell.data for cell in msh.cells if cell.type=="triangle"))
plt.figure(figsize=(8,8))
plt.triplot(msh.points[:, 0], msh.points[:, 1], cells_tri)
plt.show()
```

gives 

```
Traceback (most recent call last):
  File ".\generate_circ_square_pygmsh.py", line 9, in <module>
    msh = pygmsh.generate_mesh(geom, geo_filename=os.path.join(filepath, "trial.geo"))
  File "C:\Users\bshri\AppData\Local\Programs\Python\Python37\lib\site-packages\pygmsh\helpers.py", line 144, in generate_mesh
    mesh = meshio.read(msh_filename)
  File "C:\Users\bshri\AppData\Local\Programs\Python\Python37\lib\site-packages\meshio\_helpers.py", line 68, in read
    return reader_map[file_format](filename)
  File "C:\Users\bshri\AppData\Local\Programs\Python\Python37\lib\site-packages\meshio\gmsh\main.py", line 17, in read
    mesh = read_buffer(f)
  File "C:\Users\bshri\AppData\Local\Programs\Python\Python37\lib\site-packages\meshio\gmsh\main.py", line 47, in read_buffer
    return reader.read_buffer(f, is_ascii, data_size)
  File "C:\Users\bshri\AppData\Local\Programs\Python\Python37\lib\site-packages\meshio\gmsh\_gmsh41.py", line 60, in read_buffer
    physical_tags = _read_entities(f, is_ascii, data_size)
  File "C:\Users\bshri\AppData\Local\Programs\Python\Python37\lib\site-packages\meshio\gmsh\_gmsh41.py", line 117, in _read_entities
    physical_tags[d][tag] = list(fromfile(f, c_int, num_physicals))
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

```

Seems like an installation issue?

**Comment by nschloe** [comment]
Yes. It works well on my side.

**Comment by bhaveshshrimali** [comment]
Thanks. It turns out I had multiple versions of Gmsh on the path. I tested the above code independently on another machine and it works! Also, removing the older version makes it work as well! 

Thanks for the prompt response
