### ISSUE TITLE
Installtion on Mac OS 

### ISSUE THREAD

**Issue by beckerrh** [nschloe/pygmsh#376]
Hello,
I have trouble with installation via pip.
It seems to try to install "gmsh-4.7.0-MacOSX-sdk.tgz", but this fails, see error message below.
```
% pip install pygmsh
Collecting pygmsh
  Downloading pygmsh-7.0.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 892 kB/s 
Collecting gmsh
  Downloading gmsh-4.7.0.post3.tar.gz (10 kB)
Collecting meshio<5,>=4
  Downloading meshio-4.2.2-py3-none-any.whl (142 kB)
     |████████████████████████████████| 142 kB 3.2 MB/s 
Requirement already satisfied: numpy>=1.9 in /usr/local/lib/python3.8/site-packages (from pygmsh) (1.19.2)
Building wheels for collected packages: gmsh
  Building wheel for gmsh (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/55/f82gb1x11cd98nx1ncbn5dvh0000gn/T/pip-install-ake6sdhm/gmsh/setup.py'"'"'; __file__='"'"'/private/var/folders/55/f82gb1x11cd98nx1ncbn5dvh0000gn/T/pip-install-ake6sdhm/gmsh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/55/f82gb1x11cd98nx1ncbn5dvh0000gn/T/pip-wheel-37xdrvfc
       cwd: /private/var/folders/55/f82gb1x11cd98nx1ncbn5dvh0000gn/T/pip-install-ake6sdhm/gmsh/
  Complete output (38 lines):
  running bdist_wheel
  running build
  running build_scripts
  creating build
  creating build/scripts-3.8
  copying and adjusting gmsh -> build/scripts-3.8
  changing mode of build/scripts-3.8/gmsh from 644 to 755
  installing to build/bdist.macosx-10.15-x86_64/wheel
  running install
  Downloading https://gmsh.info/bin/MacOSX/gmsh-4.7.0-MacOSX-sdk.tgz, please wait...
  /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'gmsh.info'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    warnings.warn(
  Extracting gmsh-4.7.0-MacOSX-sdk.tgz, please wait...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/55/f82gb1x11cd98nx1ncbn5dvh0000gn/T/pip-install-ake6sdhm/gmsh/setup.py", line 87, in <module>
      setup(name            = 'gmsh',
    File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 326, in run
      self.run_command('install')
    File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/55/f82gb1x11cd98nx1ncbn5dvh0000gn/T/pip-install-ake6sdhm/gmsh/setup.py", line 50, in run
      self._extract()
    File "/private/var/folders/55/f82gb1x11cd98nx1ncbn5dvh0000gn/T/pip-install-ake6sdhm/gmsh/setup.py", line 63, in _extract
      tar = tarfile.open(fname) if ext == '.tgz' else zipfile.ZipFile(fname, 'r')
    File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tarfile.py", line 1606, in open
      raise ReadError("file could not be opened successfully")
  tarfile.ReadError: file could not be opened successfully
  ----------------------------------------
  ERROR: Failed building wheel for gmsh
```

**Comment by nschloe** [comment]
Looks like a gmsh issue, not pygmsh.

**Comment by beckerrh** [comment]
Yes, thank you !
I got confused, since former versions didn’t use the Gmsh package... 
Best regards
Roland

**Comment by nschloe** [comment]
I should perhaps remove that dependency, most people use the system version anyway.

**Comment by beckerrh** [comment]
Maybe, but the Gmsh package is supposed to work anyway (I have not tried to install Gmsh other than by pip now), I have submitted an issue to them.
Best,
Roland

**Comment by beckerrh** [comment]
Hi again, it’s working now, Christophe Geuzaine has corrected Gmsh.
Best, Roland

**Comment by kinnala** [comment]
> I should perhaps remove that dependency, most people use the system version anyway.

So is it still possible to use `pygmsh` without `gmsh` (the PyPI package)?

I cannot use `pygmsh` anymore on NixOS because `gmsh` (the PyPI package) distributes binaries that link to some Ubuntu-only versions of the libraries and `import gmsh` raises an exception. This is obviously an issue with `gmsh` package but just wondering if it's possible to skip it as you suggest?

**Comment by nschloe** [comment]
> So is it still possible to use pygmsh without gmsh (the PyPI package)?

You can keep using pygmsh 6. Version 7 and further will depend on the gmsh Python module. You could try installing gmsh with pip, `pip install gmsh`.

**Comment by kinnala** [comment]
Thanks. The installation of `gmsh` works fine but the package seems link to OS-level libraries such as `libXinerama`, `libXcursor` and `libGLU`. Normally it's fine, most distributions have these, but seems that `gmsh` (the PyPI package) expects different/newer versions than what NixOS stable has; most likely whatever is available currently in Ubuntu repositories. I need to look into it further but for now I just rely on `pygmsh 6` locally and run `pygmsh 7` inside Ubuntu container.
