### ISSUE TITLE
Geometry._SIZE_QUEUE does not respect boolean operations

### ISSUE THREAD

**Issue by jorgensd** [nschloe/pygmsh#414]
MWE.
```python
import pygmsh

# Clear previous model
mesh_size = 0.1
geom = pygmsh.occ.Geometry()
model3D = geom.__enter__()
box0 =  model3D.add_box([0.0, 0, 0], [1, 1, 1], mesh_size=mesh_size)
box1 =  model3D.add_box([0.5, 0.5, 1], [0.5, 0.5, 1], mesh_size=mesh_size)
ball = model3D.add_ball([0.5, 0.5, 0.5], 0.25, mesh_size=mesh_size)

union = model3D.boolean_union([box0, box1])
union_minus_ball = model3D.boolean_fragments(union, ball)
model3D.synchronize()

model3D.add_physical(union, "Union")
model3D.add_physical(union_minus_ball, "Union minus ball")
import gmsh
print(gmsh.model.getEntities(dim=3))
geom.generate_mesh(dim=3)
gmsh.write("mesh3D.msh")
```
As size queue is added for each box, entities are still in the size_queue, causing pygmsh to crash during mesh generation

**Comment by nschloe** [comment]
Even smaller MWE:
```python
import pygmsh

with pygmsh.occ.Geometry() as geom:
    box0 = geom.add_box([0.0, 0, 0], [1, 1, 1])
    box1 = geom.add_box([0.5, 0.5, 1], [0.5, 0.5, 1], mesh_size=0.1)
    union = geom.boolean_union([box0, box1])
    mesh = geom.generate_mesh()
```
```
Error   : Unknown model region with tag 2
Traceback (most recent call last):
  File "/home/nschloe/rcs/pygmsh/a.py", line 8, in <module>
    mesh = geom.generate_mesh()
  File "/home/nschloe/rcs/pygmsh/pygmsh/common/geometry.py", line 327, in generate_mesh
    gmsh.model.getBoundary(item.dim_tags, False, False, True), size
  File "/usr/local/lib/gmsh.py", line 755, in getBoundary
    raise Exception(logger.getLastError())
Exception: Unknown model region with tag 2
```
