### ISSUE TITLE
error when printing a generated mesh in msh format

### ISSUE THREAD

**Issue by capitalaslash** [nschloe/pygmsh#432]
With this code

```python
import pygmsh

with pygmsh.geo.Geometry() as geom:
    geom.add_polygon(
        [
            [0.0, 0.0],
            [1.0, -0.2],
            [1.1, 1.2],
            [0.1, 0.7],
        ],
        mesh_size=0.1,
    )
    mesh = geom.generate_mesh()

    mesh.write("mesh.msh")
```

I get an error

```
Traceback (most recent call last):
  File "/home/aslash/sandbox/meshio_test/./test.py", line 15, in <module>
    mesh.write("mesh.msh")
  File "/home/aslash/.local/lib/python3.9/site-packages/meshio/_mesh.py", line 170, in write
    write(path_or_buf, self, file_format, **kwargs)
  File "/home/aslash/.local/lib/python3.9/site-packages/meshio/_helpers.py", line 147, in write
    return writer(filename, mesh, **kwargs)
  File "/home/aslash/.local/lib/python3.9/site-packages/meshio/gmsh/main.py", line 111, in <lambda>
    "gmsh": lambda f, m, **kwargs: write(f, m, "4.1", **kwargs),
  File "/home/aslash/.local/lib/python3.9/site-packages/meshio/gmsh/main.py", line 102, in write
    writer.write(filename, mesh, binary=binary, float_fmt=float_fmt)
  File "/home/aslash/.local/lib/python3.9/site-packages/meshio/gmsh/_gmsh41.py", line 358, in write
    _write_nodes(fh, mesh.points, mesh.cells, mesh.point_data, float_fmt, binary)
  File "/home/aslash/.local/lib/python3.9/site-packages/meshio/gmsh/_gmsh41.py", line 610, in _write_nodes
    raise WriteError(
meshio._exceptions.WriteError: Specify entity information to deal with more than one cell type
```

that should be solved by adding `gmsh:dim_tags` to the mesh.

**Comment by nschloe** [comment]
Dup of https://github.com/nschloe/pygmsh/issues/427.
