### ISSUE TITLE
[Mixed-type mesh] make pygmsh optionally returns meshio object

### ISSUE THREAD

**Issue by BinWang0213** [nschloe/pygmsh#437]
Hi,

I'm using pygmsh and native gmsh api to generate recombined hex-dominant mesh. I may have mixed-type element (say, Hex + Prism).

So this will trigger an error in extract_to_meshio(): https://github.com/nschloe/pygmsh/blob/b869ab37f348c30cc2b26c75bdf4cdded87574ae/pygmsh/helpers.py#L102

Could you make generate_mesh() optionally returns meshio object?

**Comment by nschloe** [comment]
MWE please.

**Comment by BinWang0213** [comment]
Here you go
[test.zip](https://github.com/nschloe/pygmsh/files/6111986/test.zip)
```
Info    : Reading 'sf.pos'...
Info    : Done reading 'sf.pos'
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    mesh = geom.generate_mesh()
  File "D:\anaconda3\lib\site-packages\pygmsh\common\geometry.py", line 363, in generate_mesh
    return extract_to_meshio()
  File "D:\anaconda3\lib\site-packages\pygmsh\helpers.py", line 102, in extract_to_meshio
    assert len(elem_types) == 1
AssertionError
```
