### ISSUE TITLE
add_surface with occ geometry kernel broken

### ISSUE THREAD

**Issue by cc-a** [nschloe/pygmsh#567]
Minimal example:

```python
import pygmsh

with pygmsh.occ.geometry.Geometry() as geom:
    p0 = geom.add_point((0, 0, 0))
    p1 = geom.add_point((-1, 0, 0))
    p2 = geom.add_point((-1, 3, 0))

    l0 = geom.add_line(p0, p1)
    l1 = geom.add_line(p1, p2)
    l2 = geom.add_line(p2, p0)

    cv = geom.add_curve_loop([l0, l1, l2])
    geom.add_surface(cv)
```

This gives:

> Traceback (most recent call last):
>   File "/home/ccaveayl/projects/Solidity-GUI/experiment.py", line 15, in <module>
>     geom.add_surface(cv)
>   File "/home/ccaveayl/projects/Solidity-GUI/.venv/lib/python3.10/site-packages/pygmsh/common/geometry.py", line 92, in add_surface
>     return Surface(self.env, *args, **kwargs)
>   File "/home/ccaveayl/projects/Solidity-GUI/.venv/lib/python3.10/site-packages/pygmsh/common/surface.py", line 29, in __init__
>     self._id = env.addSurfaceFilling([self.curve_loop._id])
>   File "/usr/share/gmsh/api/python/gmsh.py", line 7078, in addSurfaceFilling
>     c_int(wireTag),
> TypeError: 'list' object cannot be interpreted as an integer

Running the above but using the geo kernel works fine. The underlying cause seems to be differing arguments for [gmsh.model.geo.addSurfaceFilling](https://gitlab.onelab.info/gmsh/gmsh/blob/master/api/gmsh.py#L5626) and [gmsh.model.occ.addSurfaceFilling](https://gitlab.onelab.info/gmsh/gmsh/blob/master/api/gmsh.py#L7070).

**Comment by hvasbath** [comment]
Same issue here.
