### ISSUE TITLE
Error with set_mesh_size_callback

### ISSUE THREAD

**Issue by lucascbarbosa** [nschloe/pygmsh#569]
I'm having trouble using `set_mesh_size_callback`. My code is: 
```
geom.set_mesh_size_callback(
            lambda dim, tag, x, y, z: pixel_size
        )
```
And the error is: 
```Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Users\lucas.barbosa\.conda\envs\deeplearn37\lib\site-packages\gmsh.py", line 3164, in <lambda>
    api_callback_ = api_callback_type_(lambda dim, tag, x, y, z, lc, _ : callback(dim, tag, x, y, z, lc))
TypeError: <lambda>() takes 5 positional arguments but 6 were given
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >
```

**Comment by erfanhamdi** [comment]
did you solve this issue? because I am having the same problem.
